# Generated by Django 5.2.4 on 2025-08-22 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('products', '0002_productcategory_description_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='discount',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='discount',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_type_en',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], null=True, verbose_name='Discount Type'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_type_ru',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], null=True, verbose_name='Discount Type'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_type_uz',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], null=True, verbose_name='Discount Type'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active_en',
            field=models.BooleanField(default=True, verbose_name='Discount Is Active'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active_ru',
            field=models.BooleanField(default=True, verbose_name='Discount Is Active'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active_uz',
            field=models.BooleanField(default=True, verbose_name='Discount Is Active'),
        ),
        migrations.AddField(
            model_name='discount',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Discount Name'),
        ),
        migrations.AddField(
            model_name='discount',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Discount Name'),
        ),
        migrations.AddField(
            model_name='discount',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Discount Name'),
        ),
        migrations.AddField(
            model_name='discount',
            name='value_en',
            field=models.PositiveIntegerField(null=True, verbose_name='Discount Value'),
        ),
        migrations.AddField(
            model_name='discount',
            name='value_ru',
            field=models.PositiveIntegerField(null=True, verbose_name='Discount Value'),
        ),
        migrations.AddField(
            model_name='discount',
            name='value_uz',
            field=models.PositiveIntegerField(null=True, verbose_name='Discount Value'),
        ),
        migrations.AddField(
            model_name='order',
            name='notes_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_at_ru',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_at_uz',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.promocode'),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.promocode'),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.promocode'),
        ),
        migrations.AddField(
            model_name='order',
            name='purchased_at_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='purchased_at_ru',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='purchased_at_uz',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_en',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_ru',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_uz',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount_en',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount_ru',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount_uz',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='payments.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='payments.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='payments.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_en',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_ru',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_uz',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_uz',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='discount_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_discounts', to='payments.discount', verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='discount_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_discounts', to='payments.discount', verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='discount_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_discounts', to='payments.discount', verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='product_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='discounts', to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='product_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='discounts', to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='product_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='discounts', to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='valid_from_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid From'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='valid_from_ru',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid From'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='valid_from_uz',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid From'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='valid_until_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid Until'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='valid_until_ru',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid Until'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='valid_until_uz',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid Until'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='promocode_id_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usages', to='payments.promocode', verbose_name='PromoCode'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='promocode_id_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usages', to='payments.promocode', verbose_name='PromoCode'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='promocode_id_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usages', to='payments.promocode', verbose_name='PromoCode'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='used_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Used At'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='used_at_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Used At'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='used_at_uz',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Used At'),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Provider Name'),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Provider Name'),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Provider Name'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_en',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_ru',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_uz',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancelled_at_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled at'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancelled_at_ru',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled at'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancelled_at_uz',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled at'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid_at_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid at'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid_at_ru',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid at'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid_at_uz',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid at'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status_en',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status_ru',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status_uz',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], verbose_name='Discount Type'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Discount Is Active'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Discount Name'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Discount Value'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_discounts', to='payments.discount', verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='discounts', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid Until'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='PromoCode'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Min Amount'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], verbose_name='Promocode Type'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage Limit'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid Until'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Promocode Value'),
        ),
        migrations.AlterField(
            model_name='promocodeusage',
            name='promocode_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usages', to='payments.promocode', verbose_name='PromoCode'),
        ),
        migrations.AlterField(
            model_name='promocodeusage',
            name='used_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Used At'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Provider Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
