# Generated by Django 5.2.4 on 2025-08-22 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_description_en_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='users.cart', verbose_name='cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='users.cart', verbose_name='cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='users.cart', verbose_name='cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity_en',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity_ru',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity_uz',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_en',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_ru',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_uz',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_en',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_ru',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_uz',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourites_en',
            field=models.ManyToManyField(null=True, related_name='favourite_users', through='users.UserFavorites', to='products.productvariant', verbose_name='favourites'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourites_ru',
            field=models.ManyToManyField(null=True, related_name='favourite_users', through='users.UserFavorites', to='products.productvariant', verbose_name='favourites'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourites_uz',
            field=models.ManyToManyField(null=True, related_name='favourite_users', through='users.UserFavorites', to='products.productvariant', verbose_name='favourites'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_en',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_ru',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_uz',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_confirmed_en',
            field=models.BooleanField(default=False, verbose_name='Is Confirmed'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_confirmed_ru',
            field=models.BooleanField(default=False, verbose_name='Is Confirmed'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_confirmed_uz',
            field=models.BooleanField(default=False, verbose_name='Is Confirmed'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff_en',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff_ru',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff_uz',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser_en',
            field=models.BooleanField(default=False, verbose_name='Is Superuser'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser_ru',
            field=models.BooleanField(default=False, verbose_name='Is Superuser'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser_uz',
            field=models.BooleanField(default=False, verbose_name='Is Superuser'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_uz',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='profession_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='users.profession', verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='user',
            name='profession_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='users.profession', verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='user',
            name='profession_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='users.profession', verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='users.cart', verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(related_name='favourite_users', through='users.UserFavorites', to='products.productvariant', verbose_name='favourites'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Is Confirmed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Is Superuser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='users.profession', verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='Product Variant'),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='message',
            field=models.CharField(max_length=500, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='UserFavorites_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='Product Variant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Favorite [en]',
                'verbose_name_plural': 'User Favorites [en]',
                'db_table': 'users_userfavorites_en',
                'db_tablespace': '',
                'auto_created': False,
                'unique_together': {('user', 'product_variant')},
            },
        ),
        migrations.CreateModel(
            name='UserFavorites_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='Product Variant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Favorite [ru]',
                'verbose_name_plural': 'User Favorites [ru]',
                'db_table': 'users_userfavorites_ru',
                'db_tablespace': '',
                'auto_created': False,
                'unique_together': {('user', 'product_variant')},
            },
        ),
        migrations.CreateModel(
            name='UserFavorites_uz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='Product Variant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Favorite [uz]',
                'verbose_name_plural': 'User Favorites [uz]',
                'db_table': 'users_userfavorites_uz',
                'db_tablespace': '',
                'auto_created': False,
                'unique_together': {('user', 'product_variant')},
            },
        ),
    ]
