# Generated by Django 5.2.4 on 2025-08-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='logo_en',
            field=models.ImageField(null=True, upload_to='sponsors', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo_ru',
            field=models.ImageField(null=True, upload_to='sponsors', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo_uz',
            field=models.ImageField(null=True, upload_to='sponsors', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to='sponsors', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
