# Generated by Django 5.2.4 on 2025-08-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_is_active_en_blogcategory_is_active_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='is_active_en',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='is_active_ru',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='is_active_uz',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_ru',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_uz',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='category_uz',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image_uz',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_featured_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_featured_ru',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_featured_uz',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published_at_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published_at_ru',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published_at_uz',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='status_ru',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='status_uz',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags_ru',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags_uz',
        ),
        migrations.AddField(
            model_name='comment',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Comment text'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Comment text'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Comment text'),
        ),
    ]
