# Generated by Django 5.2.4 on 2025-08-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='image_uz',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='is_active_en',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='is_active_ru',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='is_active_uz',
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='size'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='size'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='size'),
        ),
    ]
